# Generated by Django 3.2.9 on 2021-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211207_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='App_Name',
            new_name='Application',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='NotiTrigger',
            new_name='Notification',
        ),
        migrations.AlterField(
            model_name='query',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='expiry',
            field=models.DateField(),
        ),
    ]
